# Generated by Django 4.2.1 on 2023-05-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('min_health', models.IntegerField(default=0)),
                ('max_health', models.IntegerField(default=9)),
                ('min_money', models.IntegerField(default=0)),
                ('max_money', models.IntegerField(default=9)),
                ('min_morality', models.IntegerField(default=0)),
                ('max_morality', models.IntegerField(default=9)),
                ('health_change', models.IntegerField(default=0)),
                ('money_change', models.IntegerField(default=0)),
                ('morality_change', models.IntegerField(default=0)),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='game.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question')),
            ],
        ),
    ]
