# Generated by Django 4.2.1 on 2023-05-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='health_change',
            field=models.IntegerField(default=0, verbose_name='Изменение здоровья'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='max_health',
            field=models.IntegerField(default=9, verbose_name='Максимальное здоровье'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='max_money',
            field=models.IntegerField(default=9, verbose_name='Максимальные деньги'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='max_morality',
            field=models.IntegerField(default=9, verbose_name='Максимальная нравственность'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='min_health',
            field=models.IntegerField(default=0, verbose_name='Минимальное здоровье'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='min_money',
            field=models.IntegerField(default=0, verbose_name='Минимальные деньги'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='min_morality',
            field=models.IntegerField(default=0, verbose_name='Минимальная нравственность'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='money_change',
            field=models.IntegerField(default=0, verbose_name='Изменение денег'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='morality_change',
            field=models.IntegerField(default=0, verbose_name='Изменение нравственности'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='game.question', verbose_name='Следующий вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
