# Generated by Django 4.2.1 on 2023-05-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_question_id',
            new_name='current_question',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='telegram_chat_id',
            new_name='user_id',
        ),
    ]
