# Generated by Django 4.2.1 on 2023-05-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_current_question_id_player_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_name',
            field=models.CharField(default='username', max_length=200, verbose_name='Имя пользователя Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='current_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Текущий вопрос'),
        ),
    ]
