# Generated by Django 4.2.1 on 2023-06-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_user_name_alter_player_current_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
