# Generated by Django 4.2.1 on 2023-06-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='game.question', verbose_name='Следующий вопрос'),
            preserve_default=False,
        ),
    ]
