# Generated by Django 4.2.1 on 2023-06-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_delete_player'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='current_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Текущий вопрос'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='health',
            field=models.IntegerField(default=5, verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='money',
            field=models.IntegerField(default=5, verbose_name='Деньги'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='morality',
            field=models.IntegerField(default=5, verbose_name='Нравственность'),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
